### PR TITLE
Simplify Version command

### LINKED ISSUE #122: Simplify Version command
Currently, The version of the cmd tool is set using an additional function which can be seen [here](https://github.com/hellofresh/klepto/blob/master/cmd/version.go#L11).

The Cobra Library already has a feature to set the version using the underlying struct field `Version`.

>  // Version defines the version for this command. If this value is non-empty and the command does not
     // define a "version" flag, a "version" boolean flag will be added to the command and, if specified,
     // will print content of the "Version" variable. A shorthand "v" flag will also be added if the
    // command does not define one.
````
    Version string
````
Official docs: https://github.com/spf13/cobra/blob/5cdf8e26ba7046dd743463f60102ab52602c6428/command.go#L90

My proposal to improve it : 

```go

	// RootCmd steals and anonymises databases
	RootCmd = &cobra.Command{
		Use:     "klepto",
		Version: version,  <======== Sets the version 
         .......
        ..................
}
```
I have already tested it and working as expected. Please check the output below:

```sh
$ ./testklepto --version
klepto version 0.0.0-dev
```

### PR DESCRIPTION
**Pull request by itsksaurabh**
closes #122

### CODE REVIEW

**Comment by boekkooi-fresh** [comment]
:+1: This replace the `version` command with the `--version` flags. 
Because of the removal of the `version` command this is actually a BC break so let's include this in 0.3.0.

**Comment by itsksaurabh** [comment]
@boekkooi-fresh I am glad that you liked it. Awaiting merge. 😇

**Comment by vgarvardt** [comment]
@itsksaurabh thank you for the contribution!

ldflags should be fixed as well, as version is injected in the compile-time https://github.com/hellofresh/klepto/blob/master/.goreleaser.yml#L13

**Comment by itsksaurabh** [comment]
@vgarvardt I am glad that you liked it.

The `version` variable is already in the same `cmd` package just shifted to [root.go](https://github.com/itsksaurabh/klepto/blob/master/cmd/root.go#L14) in the same package. 

So, I think it is not needed to change ldflags  [here](https://github.com/hellofresh/klepto/blob/master/.goreleaser.yml#L13).

Please let me know if I am missing something :)

**Comment by vgarvardt** [comment]
@itsksaurabh true this, sorry

**Pull request merged**
